<h1>Ajouter une pizza</h1>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('adminpizza'));

if ($this->nom) :
    ?>
    <div>
        <p>Nom de la pizza : <?php echo $this->nom; ?></p>
    </div>
    <?php
endif;

echo $this->form()->openTag($form);
if ($form->has('nom')) :
echo $this->formLabel($form->get('nom'));
echo $this->formInput($form->get('nom'));
echo $this->formElementErrors($form->get('nom'));
endif;
echo $this->formLabel($form->get('base'));
echo $this->formSelect($form->get('base'));
echo $this->formElementErrors($form->get('base'));
echo $this->formMultiCheckbox($form->get('ingredients'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();