<h1>Ajouter une pizza</h1>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url());

echo $this->form()->openTag($form);  ?>
<form class="form-horizontal">
    <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
            <?php echo $this->formLabel($form->get('nom')); ?>
            <?php echo $this->formInput($form->get('nom')); ?>
        </div>
    </div>

    <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
            <?php echo $this->formLabel($form->get('base')); ?>
            <?php echo $this->formSelect($form->get('base')); ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
                <?php echo $this->formRow($form->get('fileupload')); ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
                <?php echo $this->formMultiCheckbox($form->get('ingredients')); ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
            <div class="checkbox">
                <?php echo $this->formLabel($form->get('pizofday')); ?>
                <?php echo $this->formCheckbox($form->get('pizofday')); ?>
            </div>
        </div>
    </div>
        <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
            <div class="checkbox">
                <?php echo $this->formLabel($form->get('pizza_au_menu')); ?>
<?php echo $this->formCheckbox($form->get('pizza_au_menu')); ?>
            </div>
        </div>
    </div>
        <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
            <?php echo $this->formLabel($form->get('prix')); ?>
                        <?php echo $this->formInput($form->get('prix')); ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-offset-2 col-xs-10">
            <?php echo $this->formSubmit($form->get('submit')); ?>
        </div>
    </div>
</form>

<?php echo $this->form()->closeTag(); ?>