 <table class="table">
 <tr>
     <th>Id</th>
     <th>Nom</th>
     <th>Url</th>
     <th>&nbsp;</th>
 </tr>
 <?php $publicDir = getcwd() . './img/img_pizzas/'; foreach ($pizzas as $pizza) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($pizza->id);?></td>
     <td><?php echo $this->escapeHtml($pizza->nom);?></td>
     <td><img src="/img/img_pizzas/<?php echo $this->escapeHtml($pizza->url_img); ?>" alt="<?php echo $this->escapeHtml($pizza->nom);?>" width="250"></td>
 </tr>
 <?php endforeach; ?>
 </table>
