<table class="table">
 <tr>
     <th>Adresse</th>   
     <th>Telephone</th> 
     <th>Email</th> 
 </tr>
 <?php foreach ($localisation as $info) : ?>
 <tr>
     <td><?php echo $Adresse= $this->escapeHtml($info->getAdresse());?></td>  
     <td><?php echo $Numero_Tel= $this->escapeHtml($info->getNumero_Tel());?></td>  
     <td><?php echo $Email= $this->escapeHtml($info->getEmail());?></td>  
 </tr>
 <?php endforeach; ?>
  
</table>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDwzHV97qF8QHCVxh6mpT2pdcQBh2HVh8o&callback=initMap"></script>
<div id="map_canvas" style="float:right;height:220px;width:45%"></div>
<script type="text/javascript">
    
  var geocoder;
  var map;
  var address = "<?php echo $Adresse ?>";
  function initialize() {
    geocoder = new google.maps.Geocoder();
//    var latlng = new google.maps.LatLng(-34.397, 150.644);
    var myOptions = {
      zoom: 16,
//      center: latlng,
    mapTypeControl: true,
    mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU},
    navigationControl: true,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    if (geocoder) {
      geocoder.geocode( { 'address': address}, function(results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
          if (status != google.maps.GeocoderStatus.ZERO_RESULTS) {
          map.setCenter(results[0].geometry.location);

            var infowindow = new google.maps.InfoWindow(
                { content: '<b>'+address+'</b>',
                  size: new google.maps.Size(150,50)
                });

            var marker = new google.maps.Marker({
                position: results[0].geometry.location,
                map: map, 
                title:address
            }); 
            google.maps.event.addListener(marker, 'click', function() {
                infowindow.open(map,marker);
            });

          } else {
            alert("No results found");
          }
        } else {
          alert("Geocode was not successful for the following reason: " + status);
        }
      });
    }
  }
</script>
<body style="margin:0px; padding:0px;" onload="initialize()">


