<div class="container">
    
<div id="article">
    
    

<div id="products" class="row list-group">
    <?php foreach ($listepizza_page as $pizza) : 
                
                $base= $this->escapeHtml($pizza->getBase()->getId()); 
                
                if($base != $base2 ) { echo "<div id=\"basetitre\" class=\"col-xs-12 col-lg-12 well\"><h1>".$this->escapeHtml($pizza->getBase()->getNom())."</h1></div>"; } ?>
    
        <div class="item  col-xs-4 col-lg-4">
            <div class="thumbnail">
               <img class="group list-group-image" src="<?php echo ROOT_PATH . "img/img_pizzas/" . $this->escapeHtml($pizza->getUrl_img()); ?>" alt="<?php echo $this->escapeHtml($pizza->getNom());?>" height="300px">
                <div class="caption">
                    <h4 class="group inner list-group-item-heading">
                        <?php echo $this->escapeHtml($pizza->getNom());?></h4>
                    <p class="group inner list-group-item-text">Les ingrédients : <?php foreach ($pizza->getIngredients() as $ingredient) : 
    
    echo " ".$ingredient->getNom() . "-";
                    endforeach; ?></p>
                    <div class="row">
                        <div class="col-xs-12 col-md-6">
                            <p class="lead">
                                <?php echo $this->escapeHtml($pizza->getPrix());?>€</p>
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <a class="btn btn-success" onclick="popup(<?php echo $this->escapeHtml($pizza->getId());?>)" href="#">Ajouter au panier</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
 <?php $base2 = $this->escapeHtml($pizza->getBase()->getId()); endforeach; ?>   
    

</div></div></div>