
<?php
  $form = $this->form;
      $form->prepare();
    $form->setAttribute('action', $this->url('register'));
    echo $this->form()->openTag($form);
?>
<table>

    <theader>

        <h1>Connexion :</h1>
    </theader>
    <tfoot>
        <tr>
            <td colspan="2">
<?php echo $this->formSubmit($form->get('submit2')); ?>
            </td>
        </tr>
    </tfoot>
    <tbody>
    
    <tr>
        <th><?php echo $this->formLabel($form->get('email')); ?>
        </th>
        <td>
            <p>
<?php echo $this->formInput($form->get('email')); ?>

            </p>    
<?php echo $this->formElementErrors($form->get('email'), array('class' => 'error_list')); ?>
        </td>

    </tr>
    <tr>
        <th><?php echo $this->formLabel($form->get('password')); ?></th>
        <td>
            <p>
<?php echo $this->formInput($form->get('password')); ?>

            </p>
<?php echo $this->formElementErrors($form->get('password'), array('class' => 'error_list')); ?>
        </td>

    </tr>
  

</tbody>
</table>
<?php
echo $this->form()->closeTag();
?>