<h1>Ajouter une pizza</h1>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('test'));

if ($this->nom) :
    ?>
    <div>
        <p>Nom de la pizza : <?php echo $this->nom; ?></p>
    </div>
    <?php
endif; ?>

<?php echo $this->form()->openTag($form) ?>
    <?php if ($form->has('nom')) : ?>
        <?php echo $this->formLabel($form->get('nom')) ?>
        <?php echo $this->formInput($form->get('nom')) ?>
        <?php echo $this->formElementErrors($form->get('nom')) ?>
    <?php endif; ?>
    <?php echo $this->formLabel($form->get('base')) ?>
<?php
        echo $this->formSelect($form->get('base'));
        echo $this->formElementErrors($form->get('base'));
    ?>
    <?php echo $this->formSubmit($form->get('submit')) ?>
<?php echo $this->form()->closeTag() ?>