<?php
    $this->headLink()->appendStylesheet('/css/fam-icons.css');
?>
<div class="container">
    <h2>Accueil</h2>
    <div class="row">
        <div class="span3">
            <a href="/adminpizza"><i class="fam-cog"></i> Admin pizza</a>
        </div>
        <div class="span9">
            Accès au CRUD pizza
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="span3">
            <a href="#"><i class="fam-page"></i> Admin commandes</a>
        </div>
        <div class="span9">
            Accès à la gestion des commandes
        </div>
    </div>
</div>