<?php
    $this->headLink()->appendStylesheet('/css/fam-icons.css');
?>
<div class="container">
    <h2>Accueil</h2>
    <div class="row">
        <div class="span3">
            <a href="/backend/adminpizza"><i class="fam-cog"></i> Admin pizza</a>
        </div>
        <div class="span9">
            Accès au CRUD pizza
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="span3">
            <a href="/backend/gestioncommandes"><i class="fam-page"></i> Admin commandes (pas fait)</a>
        </div>
        <div class="span9">
            Accès à la gestion des commandes
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="span3">
            <a href="/backend/editlocalisation"><i class="fam-page"></i> Admin infos société</a>
        </div>
        <div class="span9">
            Editer Infos société
        </div>
    </div>
</div>